server:
  port: 83


logging:
  level:
    org.yuanqi.customerfeign83.service.PaymentFeignService: debug

spring:
  application:
    name: customer-83

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
