server:
  port: 85

spring:
  application:
    name: Customer-nacos-85

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
