server:
  port: 86

spring:
  application:
    name: customer-sentinel

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8500
    sentinel:
      transport:
        dashboard: localhost:8080

feign:
  sentinel:
    enabled: true
