server:
  port: 8004
spring:
  application:
    name: payment-8004

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率介于0-1，1表示全部采集
      probability: 1

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
