
server:
  port: 8991

spring:
  application:
    name: Stream-Customer

  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:  #*
          destination: studyExchange  #\u8981\u4F7F\u7528\u7684Exchange\u540D\u79F0
          content-type: application/json  #\u6D88\u606F\u7C7B\u578B
          binder: defaultRabbit #\u8981\u7ED1\u5B9A\u7684\u6D88\u606F\u670D\u52A1\u7684\u5177\u4F53\u8BBE\u7F6E
          group: customer


    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: receiver-8991
        prefer-ip-address: true
