server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #eurela服务端的实例名字


  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #false 表示自己就是注册中心，不需要去检索服务
    service-url:
      #设置与eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/

  server:
    enable-self-preservation: false
